version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    restart : always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: lnmp
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --skip-character-set-client-handshake
  redis:
    image: redis:7.0
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: always
    environment:
      TZ: Asia/Shanghai
      REDIS_PASSWORD: 123456
    command: bash -c 'docker-entrypoint.sh --requirepass "$${REDIS_PASSWORD}"'
  php-fpm:
    image: local/php-fpm:8.1
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    restart : always
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - mysql
      - redis
  nginx:
    image: nginx:1.23
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - php-fpm
volumes:
  mysql-data:
  redis-data:
