version: "3"
services:
  apisix-dashboard:
    image: apache/apisix-dashboard:2.13-centos
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
    - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml:ro
    ports:
    - "9000:9000"
  apisix:
    image: apache/apisix:2.99.0-centos
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - apisix_log:/usr/local/apisix/logs
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
  etcd:
    image: bitnami/etcd:3.5.5
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      TZ: Asia/Shanghai
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
  prometheus:
    image: prom/prometheus:v2.39.1
    restart : always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./prometheus_conf/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:7.3.7
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "./grafana_conf/provisioning:/etc/grafana/provisioning"
      - "./grafana_conf/dashboards:/var/lib/grafana/dashboards"
      - "./grafana_conf/config/grafana.ini:/etc/grafana/grafana.ini"
volumes:
  apisix_log:
  etcd_data:
