version: '3'
services:
  coredns:
    image: coredns/coredns:1.10.1
    ports:
      - 53:53
      - 9153:9153
      - 53:53/udp
    volumes:
      - ./config:/etc/coredns
    restart : always
    environment:
      TZ: Asia/Shanghai
    entrypoint: /coredns
    command:
      - -conf
      - /etc/coredns/Corefile
