jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  numExecutors: 0
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          name: admin
          password: 123456
  updateCenter:
    sites:
      - id: default
        url: "https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/update-center.json"
  nodes:
    - permanent:
        launcher:
          jnlp:
            workDirSettings:
              disabled: false
              failIfWorkDirIsMissing: false
              internalDir: remoting
              workDirPath: /home/jenkins/agent
        name: slave-01
        numExecutors: 5
        remoteFS: /home/jenkins
        retentionStrategy: always
  slaveAgentPort: 50000
  agentProtocols:
    - JNLP4-connect
